### ISSUE TITLE
No Longer Saving Position

### ISSUE THREAD

**Issue by dalkain** [Taschenbuch/BlishHud-SessionTracker#4] opened 2023-10-11 22:38 UTC
I recently updated to v2.3.0 and this module no longer remembers the position I've moved it to when loaded.

I did notice that it will spawn based on the new 'window anchor' setting in the extremes of the display (e.g. when set to 'Top Left' it spawns in the top left corner of my display, and set to 'Top Right' it spawns in the top right corner of the display).

Running Blish HUD v1.1.1

Let me know if any further details are required!

**Comment by brianmccarty** [comment] 2023-10-13 00:52
Same it no longer remembers the window location an instead resets

**Comment by Taschenbuch** [comment] 2023-10-13 09:47
thanks for reporting and sorry for the inconvenience caused by that. I was already informed that this issue exists, but I was not able to reproduce it on my machine until yesterday evening. Because of that I hid the bugged release from the blish hud repo for now until i can release a fixed version. 

Until I am able to fix this properly, you can use a "quickfixed" beta .bhm if you want to. I uploaded this .bhm in this discord channel:
https://discord.com/channels/531175899588984842/1009196657570746530/1161742145724612668

It can be installed manually by following these steps:
1. shutdown/exit/close blish hud
2. delete the session tracker .bhm in this folder: C:\Users\Anwender\Documents\Guild Wars 2\addons\blishhud\modules
3. copy the .bhm from the link above into that folder
4. start blish again
5. if you cannot find the stats window after installing this version, you may want to disable the module, click on the cog wheel at the top right, select "clear settings" and then enable the module again.

**Comment by Taschenbuch** [comment] 2023-10-14 10:07
it is fixed now. new release  (3.0.0) will be available probably today or tomorrow

**Closed by Taschenbuch** 2023-10-14 10:07 UTC
